DROP TABLE IF EXISTS `thesis-25-456305.raw_layer.mdl_enrol`;

CREATE TABLE `thesis-25-456305.raw_layer.mdl_enrol` (
  id INT64,
  enrol STRING,
  status INT64,
  courseid INT64,
  sortorder INT64,
  name STRING,
  enrolperiod INT64,
  enrolstartdate INT64,
  enrolenddate INT64,
  expirynotify BOOL,
  expirythreshold INT64,
  notifyall BOOL,
  password STRING,
  cost STRING,
  currency STRING,
  roleid INT64,
  customint1 INT64,
  customint2 INT64,
  customint3 INT64,
  customint4 INT64,
  customint5 INT64,
  customint6 INT64,
  customint7 INT64,
  customint8 INT64,
  customchar1 STRING,
  customchar2 STRING,
  customchar3 STRING,
  customdec1 FLOAT64,
  customdec2 FLOAT64,
  customtext1 STRING,
  customtext2 STRING,
  customtext3 STRING,
  customtext4 STRING,
  timecreated INT64,
  timemodified INT64
);
