DROP TABLE IF EXISTS `thesis-25-456305.raw_layer.mdl_course`;

CREATE TABLE `thesis-25-456305.raw_layer.mdl_course` (
  id INT64,
  category INT64,
  sortorder INT64,
  fullname STRING,
  shortname STRING,
  idnumber STRING,
  summary STRING,
  summaryformat INT64,
  format STRING,
  showgrades INT64,
  newsitems INT64,
  startdate INT64,
  enddate INT64,
  relativedatesmode BOOL,
  marker INT64,
  maxbytes INT64,
  legacyfiles INT64,
  showreports INT64,
  visible BOOL,
  visibleold BOOL,
  downloadcontent BOOL,
  groupmode INT64,
  groupmodeforce INT64,
  defaultgroupingid INT64,
  lang STRING,
  calendartype STRING,
  theme STRING,
  timecreated INT64,
  timemodified INT64,
  requested BOOL,
  enablecompletion BOOL,
  completionnotify BOOL,
  cacherev INT64,
  originalcourseid INT64,
  showactivitydates BOOL,
  showcompletionconditions BOOL,
  pdfexportfont STRING
);
